name: Build My Dylib
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install ldid xz

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH

      - name: Build Dylib
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyDylibFile
          path: .theos/obj/debug/*.dylib
